language: objective-c
os: osx
osx_image: xcode8

env:
  global:
    - IOS_FRAMEWORK_SCHEME="Raclette"
    - IOS_SDK=iphonesimulator
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"

branches:
  only:
    - master
    - development

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - travis_retry xcodebuild test -project Raclette.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c

notifications:
  email: false
